version: "3"
services:
  app:
    container_name: game-of-three
    restart: always
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/expressmongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"